### ISSUE TITLE
Forecast no longer showing time

### ISSUE THREAD

**Issue by Waank1** [Pirate-Weather/pirate-weather-ha#133]
I noticed a few days ago that the times are not displayed when I open the forecast.

Monday, August 7 (Day)                                                —     82 °F

I'm wondering if anything has changed or is it on my end.
Here is my current setup:
Home Assistant 2023.8.1
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

EDIT:  Found it was a problem with Core 2023.8.1 rolled back to 2023.7.3 and it works now.

**Comment by thd6n75** [comment]
Same here - problem occurred after upgrading HA from 2023.7.3 to anything 2023.8.x .. I'm not sure I would characterize this as a problem with HomeAssistant, though.  Perhaps HomeAssistant made a breaking change that requires an update to the Pirate Weather integration.  (Or, indeed, maybe it is a bug in HA)

**Comment by chrisfromthelc** [comment]
I am also having the same issue; I'd prefer not to need to roll back and lose feature upgrades by moving to 2023.8.

**Comment by thd6n75** [comment]
I think maybe it only manifests in the hourly view?  Where the `--` are, there used to be times, like 2:00pm, 3:00pm, etc.

![pirateweather-notimes](https://github.com/alexander0042/pirate-weather-ha/assets/35642586/f5dcd2c0-e0ef-4d6c-93a6-16ed01697bcf)

**Comment by chrisfromthelc** [comment]
I'm also seeing what @thd6n75 shows in their screenshot for the hourly entity.

**Comment by alexander0042** [comment]
Thank you, and replicated, which is step 1. Also appreciate you pointing out that tomorrow.io is working, since that gives me a template to produce a fix from. I've tagged this as a bug and will get working on a fix

**Comment by Waank1** [comment]
Just to let you know, I updated Core to 2023.8.3 and your app now is back to displaying accurately.

**Comment by thd6n75** [comment]
2023.8.3 fixed it for me, too.

**Comment by cloneofghosts** [comment]
Closing this one for cleanup. If you're still having issues feel free to re-open or crate a new issue.
