### ISSUE TITLE
The pirateweather integration is using deprecated forecast (2023.9.0b0)

### ISSUE THREAD

**Issue by TheFes** [Pirate-Weather/pirate-weather-ha#136]
HA will remove the forecast attribute, you will have to move to a new method to include the forecast

see https://developers.home-assistant.io/blog/2023/08/07/weather_entity_forecast_types/

**Comment by alexander0042** [comment]
Thanks for the heads up here! I've had my eye on the changes to the source, so great to see everything documented. The current approach leaves much to be desired, and so I'm really happy with these new updates

**Comment by Intecpsp** [comment]
Any update here now that this is GA?

**Comment by tcfurrer** [comment]
@Intecpsp it's only a warning for now, and won't be a real problem until March 2024 (if I understand correctly).  I assume @alexander0042 will prioritize/schedule this issue to be fixed in a new release some time before then.

Attaching a screenshot of the message I got about this on my HA instance.
<img width="389" alt="image" src="https://github.com/alexander0042/pirate-weather-ha/assets/39924916/2bbd4ce0-513f-4e78-82b5-cb2927de640b">

**Comment by dmbreakey** [comment]
Apologies for the repeat, but I mentioned this on #137 but it doesn't seem like that's been noticed, so adding it here.

You might be interested to know that [AstroWeather](https://github.com/mawinkler/astroweather) recently updated their integration to support the new service mode.

**Comment by TheFes** [comment]
Just a request, please leave the forecasts in until 2024.3 like the core integrations do as well.
Another custom weather integration removed it already, and I still rely on the forecast attribute for a template weather entity.

**Comment by Chaotic** [comment]
Any update on this?  Been a few months at this point since the change went live.

**Comment by alexander0042** [comment]
Apologies for the radio silence, but I've got good news here! I'm going to post a longer update as a project, but in short, I have a immediate solution to this specific issue that should address this. It keeps 95% of the same code and structure, with a little translation layer to fit it into the new Home Assistant format. I'm going to leave it running on my machine for a couple days to make sure it's working, but then I'll push it out as an update!

In the process of fixing this, I ended up spending a fair bit of time thinking about the underlying structure, and I think that it makes the most sense to restructure the integration using all the new tools. Going to push this as a branch, so will be available for discussion but won't come out as an update. This should fix the occasional update issue, remove the legacy Dark Sky dependency, and allow for it to eventually make it into the default. However, it will likely break compatibility with the existing integration, hence the fix to this one first!

**Comment by TheFes** [comment]
Will you include the forecast attribute until 2024.3 or will you immediately remove it?

**Comment by cloneofghosts** [comment]
> Apologies for the radio silence, but I've got good news here! I'm going to post a longer update as a project, but in short, I have a immediate solution to this specific issue that should address this. It keeps 95% of the same code and structure, with a little translation layer to fit it into the new Home Assistant format. I'm going to leave it running on my machine for a couple days to make sure it's working, but then I'll push it out as an update!
> 
> In the process of fixing this, I ended up spending a fair bit of time thinking about the underlying structure, and I think that it makes the most sense to restructure the integration using all the new tools. Going to push this as a branch, so will be available for discussion but won't come out as an update. This should fix the occasional update issue, remove the legacy Dark Sky dependency, and allow for it to eventually make it into the default. However, it will likely break compatibility with the existing integration, hence the fix to this one first!

You could always publish both the immediate and long term fixes as branches on the project and release beta versions for people to try as you can download beta versions in HACS. Could always be helpful for the immediate fix to test on other setups besides your own.

**Comment by alexander0042** [comment]
@TheFes, the plan is to keep this repo around so long as there's no major incompatibility within Home Assistant that makes it impossible. The key reason to transition to a new codebase to get added to the built in HA install is because of the YAML support. I want to keep this one compatible with legacy yaml, but that really isn't possible in order to be added as a new HA integration. 

@cloneofghosts, love this plan, and is exactly what I'm planning on doing. You'll see a "beta" branch today that is the existing integration, along with a (broken) "future" branch that I'll use to put together a fully HA compliant version going forward.

**Comment by alexander0042** [comment]
OK, and pre-release is live! Looks like anyone using HACS should see it if they enabled "show pre-release" when it was installed, otherwise you need to remove and re-add the Pirate Weather repo in HACS

**Comment by mermelmadness** [comment]
> OK, and pre-release is live! Looks like anyone using HACS should see it if they enabled "show pre-release" when it was installed, otherwise you need to remove and re-add the Pirate Weather repo in HACS

Great.  I'll check it out shortly.  I integrate Pirate Weather forecast attribute data into a lot of my stuff, including this LED Matrix information panel, so I'll let you know how things integrate with the update.
![IMG_6131](https://github.com/alexander0042/pirate-weather-ha/assets/38080873/fcd72c4e-9d24-4ba9-82b3-d3cc5d00c136)

**Comment by cloneofghosts** [comment]
Outside of the time sensor issue everything has been running smoothly on my end. Just wanted to note that if you're using a custom weather card it might not work correctly with the update. They'll need to update the card on their end to support the forecast attribute.

Maybe it's something that @alexander0042 could mention in the release notes or the repositories readme file.

**Comment by alexander0042** [comment]
Now that I've tested the version control (which would have been bad), I agree we're ready to push to main, and would appreciate if you could do that! I just pushed a new commit reverting my testing changes, so I think you'll have to make a new tag and mark that one as the official release

**Comment by cloneofghosts** [comment]
Version released. Thank you to everyone who tested the pre-release version.
