### ISSUE TITLE
After v1.3.1 update, sensors are not updating.

### ISSUE THREAD

**Issue by mermelmadness** [Pirate-Weather/pirate-weather-ha#142]
I updated to v1.3.1, which I know is a pre-release, but wanted to let you know that none of the sensors that are selectable from the Configure section are updating and have been static for the past 15 hours or so.

![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/38080873/3f30d09c-dd9b-4096-9a83-aba9ff846691)
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/38080873/1b112f63-69ee-4bab-b10a-479f93c2b8a8)
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/38080873/fea1d2ee-a7af-44e1-a8b3-7d515c576f21)

My config for the sensors:
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/38080873/bec387ba-7ee4-4905-b75c-0f8155d3fdb3)
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/38080873/f40d60b8-2613-4168-95de-0ceef8768ab2)

and my entry in sensors.yaml:
```
  - platform: pirateweather
    api_key: <API KEY>
    scan_interval: '00:02:15'
```

Should I try a new API key?

**Comment by alexander0042** [comment]
Good catch! I'm seeing this as well on my end, so let me investigate

**Comment by alexander0042** [comment]
Follow-up question- did you add a "time" sensor, and is it updating?

**Comment by alexander0042** [comment]
Nope, not the time sensor. I'm thinking it might have something to do with re-configuring the sensors, but not sure yet

**Comment by alexander0042** [comment]
Good thought, but luckily that's not it! The data update coordinator handles all the fetching, so no matter how many sensor or weather entities you have for a given location, it's all done in a single call. I've isolated this down to making a change using the configure button- updates stop working whenever it's configured. The key question is if this is a new issue, or something that has always been happening before 1.3

**Comment by cloneofghosts** [comment]
From my limited testing this issue seems to happen if you have the time sensor selected in your list of sensors. I was having the same issue and it seems that removing the sensor (and restarting HA) seems to have solved the issue for me. I'm going to observe it for a big longer to say conclusively if that is the issue or not.

Have you tried removing the time sensor to see if that solves your issue?

**Comment by alexander0042** [comment]
Oh interesting, I didn't try restarting. Definitely let me know if that works- first with the time sensor, then without

**Comment by mermelmadness** [comment]
Enabling `Time` without restarting freezes the sensors.

Enabling `Time` with restarting leaves the sensors frozen.

**Comment by mermelmadness** [comment]
Hmm, now nothing is updating, not even the weather entity.

![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/38080873/8e94c595-5ea8-4733-8718-9b9abf8d41cc)

**Comment by alexander0042** [comment]
Ok, I think I've got a solution here! For some reason it's not linking with the existing weather coordinator when options are changed. In the current version I had a check to see if there was an existing coordinator, but that was only there in case someone wanted both a daily and hourly forecast in their dashboard. Now that both of those are handled in one place, that's no longer required! Long story short, 1.3.2 is incoming shortly

**Comment by mermelmadness** [comment]
I see.  Ok, will look out it and test.

**Comment by mermelmadness** [comment]
1.3.2 installed and HA restarted.  I have my scan interval set to 2min 15sec and it doesn't seem to be updating at that interval.

![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/38080873/b85a02ee-4559-4e7e-a9ae-99981857a4a1)

**Comment by alexander0042** [comment]
Do you mind going to setting -> logs -> load full logs? The coordinator logs an info log every time it checks for an update, so it should show up there if it's updating

**Comment by alexander0042** [comment]
That's great! Check out those bottom lines, that's the update coordinator checking for updates every 2 seconds, which is looking promising. Also worth adding a the time sensor back in, since that should update every go

**Comment by mermelmadness** [comment]
Time sensor is back in, but is still displaying that odd 10-digit string.  The sensors are still not showing as updated recently.

**Comment by mermelmadness** [comment]
Unless I'm being too impatient.  I can let it run for a few hours and report back.

**Comment by alexander0042** [comment]
Yea, the 10-digit string is the UNIT time for the forecast. I'm not sure if HA has a better way of displaying it (maybe ISO), but it should change with every update:
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/26213938/dd75055d-8f6f-4e0c-9ba4-f87e52d463af)

**Comment by mermelmadness** [comment]
Mine isn't updating like that
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/38080873/0acfff9f-1986-4561-b861-4c3826cc4ea5)

**Comment by alexander0042** [comment]
Can you try selecting "reload" from the three dot menu on the integration page? I'm thinking that might kick it into gear

**Comment by mermelmadness** [comment]
Ok, that did it.  And now that I know it's Unix time I wrote this template to convert it to human-readable MM/DD.

```
      forecast_date_2d:
        friendly_name: "Forecast Date 2d"
        value_template: "{{ states('sensor.pirateweather_time_2d') | int | timestamp_custom('%m/%d') }}"
```

**Comment by mermelmadness** [comment]
Ok, everything seems to be working as expected now.  Thank you for your prompt responses and for maintaining this integration.
