### ISSUE TITLE
Unable to install the component

### ISSUE THREAD

**Issue by km8742** [Pirate-Weather/pirate-weather-ha#143]
Hello,
I've just tried to install the pirateweather component but got no entities after installing.

In the log file I have the following error message:
Logger: homeassistant.setup
Source: setup.py:379

Unable to prepare setup for platform pirateweather.weather: Platform not found (cannot import name 'WeatherEntityFeature' from 'homeassistant.components.weather' (/***/homeassistant/lib/python3.10/site-packages/homeassistant/components/weather/__init__.py)).

Anybody knows a fix for this problem?
Thank you very much.

**Comment by cloneofghosts** [comment]
I'll tag @alexander0042 so he can take a look at this but some helpful information to know is:

Which version of the integration are installing and what version of HA are you running?

**Comment by km8742** [comment]
Hello,
Home Assistant Version: 2023.7.3
Pirate-Weather: Version 1.3.2

**Comment by alexander0042** [comment]
Hi, thanks for opening this issue, and apologies for the issue here. The hiccup is that you're running the pre-release version of Pirate Weather, but your version of HA is tool old.

However, HACS should be able to prevent this, so let me take a look at the manifest to see what went wrong here!

**Comment by km8742** [comment]
Argh, just realized I've installed HA Core - will this even work in core?

**Comment by cloneofghosts** [comment]
The pre-release version of the integration requires HA version 2023.10 so you'd need to update your version of HA to run that version. The release version 1.2.3 will work with your HA version so have you tried installing that and seeing if it works?

I'm not a HA expert but I'll tag @alexander0042 again as he might know more information on if the integration would work in Core.

**Comment by km8742** [comment]
I've updated HA to the latest version and it's working - thanks!

**Comment by cloneofghosts** [comment]
Glad you were able to get it working. Since this issue has been solved I'm going to close this issue.
