### ISSUE TITLE
Not quite an issue, more like a discussion

### ISSUE THREAD

**Issue by ovizii** [Pirate-Weather/pirate-weather-ha#144]
Sorry for opening an issue, but discussions aren't enabled for this project so here it goes:

What cards are you using to display this weather data in home assistant besides the default built-in card? After having a look at the linked merrysky.net I'd love to have some of those details in my HA dashboard too.

**Comment by alexander0042** [comment]
Hi, thanks for using this integration and starting this discussion! It's a great question, and I should probably link to some options (this pairs well with the docs rewrite). 

The good news is that Home Assistant has a pretty standardized approach to this, so any card should work. However, I don't have any specific recommendations- MerrySky is a custom website, so I don't believe translates to Home Assistant. I'll take a look around GitHub to see what I can track down though and link back here!

**Comment by ovizii** [comment]
Thanks, I had figured that out meanwhile and simply used the default weather card, but I'm still looking for a “prettier” one with more features. Would love to hear back from you if you ever find one you can recommend. Closing this issue meanwhile.
