### ISSUE TITLE
Finish HA Documentation

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-ha#146]
The documentation for the [Home Assistant Integration](https://pirateweather.net/en/latest/ha/) needs to be completed on the Pirate Weather website as there currently is no documentation available. The readme in the repository currently links to the WayBack Machine versions of the deprecated DarkSky integration and is likely outdated with some of the changes to HA since it was deprecated.

**Comment by alexander0042** [comment]
I can't believe I forgot about this! It's a pretty visible spot, so thank you for tagging it. It won't be too hard to pull together, so I'll put it on the docket.

**Comment by jhrath** [comment]
Regarding the documentation: I still can't find a correct and full list of alternative values given by the "icon"-sensor. I see the documentation reffers to DarkSky, but it's not available. The web page (https://pirateweather.net/en/latest/API/#icon) lists possble values, but not the value I'm currently getting: "partlycloudy"
I'm using Node Red and filtering actions based on these text values, and need them all to get the correct action if "thunderstorm", "fog" and all other alternetives.

**Comment by cloneofghosts** [comment]
The documentation for HA is pretty sparse at the moment but the list of all the icons used in HA can be found here https://www.home-assistant.io/integrations/weather/#condition-mapping

I've gone ahead and tagged this as open to contributors so if anyone would like to help improve the HA documentation they can create a PR on the [website repository](https://github.com/Pirate-Weather/pirateweather) and I'll review and merge it in.
