### ISSUE TITLE
Sensor entities missing

### ISSUE THREAD

**Issue by dotmick** [Pirate-Weather/pirate-weather-ha#153]
### Describe the issue

Hi 👋

First of all, thank you for all the hard work on creating and maintaining such a great and useful project!

I've got my API key, the integration of Pirate Weather added to my HA but when I try to add a card on my dashboard, I can only see 'update.pirate_weather_update', nothing else.

Did I miss something?

Thanks!

### Home Assistant version

2023.11.3

### Integration version

1.3.4

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Can you add a screenshot of your configuration settings? When you look at the entity list for Pirate Weather what does it show you? If you've selected weather you should be able to add the default Weather Forecast card and change it to use Pirate Weather and you should have an entity called PirateWeather (weather.pirateweather) in the entity list.

**Comment by cloneofghosts** [comment]
Hi @dotmick haven't seen any updates from you since the issue was initially opened. If you have any more information feel free to re-open and we can investigate this issue.
