### ISSUE TITLE
Precip_accumulation cannot be added in HA entities

### ISSUE THREAD

**Issue by davetres** [Pirate-Weather/pirate-weather-ha#158]
### Describe the issue

I'm trying to add precip_accumulation sensor to HA but it seems it's the only one not showing in the entity list. I was able to add the following sensors without any problems:
      - temperature
      - precip_probability
      - precip_type
      - precip_intensity
 
Also, it doesn't show anything in the logs. Any ideas what can be the problem?

### Home Assistant version

2023.11.3

### Integration version

1.3.4

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Thanks for using this integration, and apologies for the issue here.
I suspect the problem is that you're using hourly sensors- accumulation should show up for the daily ones, but hourly is just intensity. This should be improved in the next release of the API, since my new ingest flow separates intensity and accumulation, but for now they're the same value, which is how Dark Sky did it

**Comment by davetres** [comment]
Ok great thanks. I will use intensity for snow accumulation then.
