### ISSUE TITLE
weather.get_forecast is deprecated as of 2023.12

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-ha#165]
### Describe the bug

As of 2023.12 weather.get_forecast is now deprecated and has been replaced with weather.get_forecasts

Information from the HA blog https://www.home-assistant.io/blog/2023/12/06/release-202312/#backward-incompatible-changes

weather.get_forecast uses an outdated response data format and is now deprecated, pending removal in Home Assistant 2024.6.

Please use weather.get_forecasts, which supports multiple entities instead.

The output of this newer service changed slightly, as it now returns a mapping of entity IDs to lists of forecasts instead of a list of forecasts.

(@eifinger - https://github.com/home-assistant/core/pull/102534) [(documentation)](https://www.home-assistant.io/integrations/weather)

### Expected behavior

See above

### Actual behavior

See above

### Home Assistant version

2023.12.3

### Integration version

1.3.5

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Good idea to open the issue to track this. I'm going to update my end (without a template) and see if it flags this issue, which will show if it's something in the integration or just the template

**Comment by cloneofghosts** [comment]
Updated my template to use `weather.get_forecasts` and the error message is gone so the issue was with the template not with the integration.
