### ISSUE TITLE
Daily Precipitation Values Incorrect

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-ha#170]
As noted in issue #166 when using imperial units the daily precipitation values are higher than what is reported in the API. Pre-release version 1.3.6b1 has been released which contains two fixes:

- Fixes the conversion from mm to inches on the daily precipitation sensor
- Fixes the conversion from cm to mm on the daily precipitation entity

If your HA is setup to use metric the values displayed in HA should be 10x higher than what the API is reporting and for imperial the values should be exactly the same as the API.

**Comment by cloneofghosts** [comment]
@K-Money I've released the stable version 1.3.6 which should hopefully solve the issue you were seeing with the precipitation accumulation. If there are still issues occurring with the imperial units then @alexander0042 would need to look into this issue.

**Comment by K-Money** [comment]
@cloneofghosts Rain is finally in the forecast and I can now confirm this has been fixed. Merry Sky reports 0.3in of rain Sat and 0.4in of rain on Sun. The Home Assistant service call reports 0.26 for Sat and 0.34 for Sun. Thank you!
