### ISSUE TITLE
"Today" HI/LOW temperature forecast

### ISSUE THREAD

**Issue by RickOSidhe** [Pirate-Weather/pirate-weather-ha#180]
### Describe the bug

The high temperature for the "today" forecast is incorrect. I think (not certain) that this occurs when switching to night from day. This is the second day in a row that I've noticed the issue.

### Expected behavior

Report correct daily forecast high temperature for current day/current night.

### Actual behavior

It appears that the high temp being forecast for current day is actually the highest temperature in the 8 day forecast period. The actual daily high temperature forecast for 1/19 (current day) reported by the MerrySky website for my location is 30F, who is located within a few miles of me. Pirate Weather is forecasting a daily high of 62F. The only forecast for a daily high of 62F at my location occurs on 1/25.

### Home Assistant version

2024.1.4

### Integration version

1.4

### Other details

![Screenshot 2024-01-21 191901](https://github.com/Pirate-Weather/pirate-weather-ha/assets/93440481/881a8df9-7bad-4716-9a33-56c5e060266f)

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by RickOSidhe** [comment]
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/93440481/f7af1cb6-7c20-48cc-997c-f85639c19ff6)

**Comment by RickOSidhe** [comment]
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/93440481/13301444-5f61-453f-9910-586e3ab30cc5)

**Comment by RollingStar** [comment]
as a temporary solution, I'm using 12h and 24h as a way to eyeball the daily high.
![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/4810902/2b3ba30d-394a-4bab-96fe-cc39e0ace24a)

**Comment by RickOSidhe** [comment]
> as a temporary solution, I'm using 12h and 24h as a way to eyeball the daily high.

Thanks for the tip. I can likely write a template sensor that reports the actual daily high, but I'd then have to implement something else that would dynamically modify the Pirate Weather get_forecast results to put the data where I'd need it. Even then, it doesn't solve the issue of a _forecast_ daily high. Better than nothing, though. Thanks again!

**Comment by cloneofghosts** [comment]
While this is an API issue that is scheduled to be fixed in V2 of the API a temporary fix could be changing it from temperatureHigh to temperatrueMax. I don't think the bug applies to temperatureMax but I can double check in a couple of hours once the bug happens to see if it's affected or not.

If it's not affected by the bug then I can update the integration (or merge a PR if anyone creates one) and release 1.4.1 with this change.

**Comment by cloneofghosts** [comment]
Did a quick test last night and can confirm that the bug doesn't apply to `temperatureMax` so I created a PR to have the integration use `temperatureMax` instead of `temperatureHigh`. Just needs to be reviewed by @alexander0042 before going live.

**Comment by RickOSidhe** [comment]
>Did a quick test last night and can confirm that the bug doesn't apply to temperatureMax so I created a PR to have the integration use temperatureMax instead of temperatureHigh. Just needs to be reviewed by @alexander0042 before going live.

That's awesome, Kev! Many thanks!

**Comment by cloneofghosts** [comment]
I've released version 1.4.1 which contains this change and should hopefully solve this issue. If the issue still occurs after the change then you'll have to wait for V2 of the API to release which will fix this isssue.
