### ISSUE TITLE
Question about Precipitation

### ISSUE THREAD

**Issue by jhemak** [Pirate-Weather/pirate-weather-ha#206]
### Describe the issue

Hi again!  Would you be able to explain the difference between the response given for the following:

precip_probability sensor value
precipitation_probability of hourly forecast hour 0
precipitation_probability of daily forecast day 0

For example, I currently have values of 0, 39, and 54 for these, respectively.  In fact, precip_probability has been zero almost all day and the others have been non-zero most of the day.  Almost makes me wonder if the sensor is even updating but for the fact that just a short time ago it popped up from 0 to 32 and back to 0 in the span of 15 minutes.  Just trying to understand how to interpret the meaning of the data provided for each (especially the first one).

Thank you!

### Home Assistant version

2024.3.2

### Integration version

1.4.5.1

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Thanks for the question. I'll add the definitions below:

`precipitation_probability` - The probability of precipitation for the current time
`precipitation_probability_h0` - The probability of precipitation for the current hour
`precipitation_probability_d0` - The average probability for the current day

I can't remember if the current precipitation probability is interpolated from the current hour to the next hour on the live API but it is on the development API. I'll ping @alexander0042 to confirm

It may be useful to add that to the API documentation as the `precipProbability` section is pretty light.

**Comment by jhemak** [comment]
Awesome - thank you for the clarification!

**Comment by cloneofghosts** [comment]
It looks like I was mistaken about the daily precipitation probability. I thought it was the average for the day but it turns out it's actually the highest precipitation probability for the day.

So if the maximum precipitation probability for a day is 73% the daily precipitation probability for the day would be 73%.

**Comment by cloneofghosts** [comment]
I've updated the API docs with that information. I'm going to close this issue now but feel free to re-open if you have any more questions about precipitation probability.
