### ISSUE TITLE
Add NWSheadline to Alerts

### ISSUE THREAD

**Issue by jhemak** [Pirate-Weather/pirate-weather-ha#208]
### Describe the feature

Hello, would you be able to add the value of NWSheadline as an attribute to the Alerts sensor?  This value should be in the NWS API response.  Thank you!

### Acknowledgements

- [X] I have searched this repository and [API Repository](https://github.com/Pirate-Weather/pirateweather/) to see if the feature has already been requested.
- [X] This featre request is sepecific to the HA Integration.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
This is very doable, but just need a little clarification about what you mean by NWSheadline? Right now I include the title, but I'm guessing it's a different field? I already have to hammer the NWS alerts API, so easy to grab another parameter!

**Comment by jhemak** [comment]
Thanks, that is what it appears to be called in the API response.  Here's a random example:

```
"parameters": {
    "AWIPSidentifier": [
        "MWWEKA"
    ],
    "WMOidentifier": [
        "WHUS76 KEKA 051004"
    ],
    "NWSheadline": [
        "GALE WARNING REMAINS IN EFFECT UNTIL 6 AM PDT EARLY THIS MORNING"
    ],
    "BLOCKCHANNEL": [
        "EAS",
        "NWEM",
        "CMAS"
    ],
    "VTEC": [
        "/O.CON.KEKA.GL.W.0025.000000T0000Z-240405T1300Z/"
    ],
    "eventEndingTime": [
        "2024-04-05T13:00:00+00:00"
    ],
    "expiredReferences": [
        "w-nws.webmaster@noaa.gov,urn:oid:2.49.0.1.840.0.f5ae1ca615f14550b18ed181ebabee70a9f0536b.002.2,2024-04-04T15:05:00-07:00 w-nws.webmaster@noaa.gov,urn:oid:2.49.0.1.840.0.f449d498e2e6da0844ef68e264805677b3293808.002.2,2024-04-04T08:59:00-07:00 w-nws.webmaster@noaa.gov,urn:oid:2.49.0.1.840.0.80916473f56c51415c2682af402f67841d7a0e98.003.2,2024-04-04T02:30:00-07:00 w-nws.webmaster@noaa.gov,urn:oid:2.49.0.1.840.0.202be32ec49962c7428a039d982e53a479fa62f9.001.3,2024-04-03T20:56:00-07:00 w-nws.webmaster@noaa.gov,urn:oid:2.49.0.1.840.0.f3708a79da9db39161aab4d7f82b5d11c7fb23aa.002.2,2024-04-03T14:30:00-07:00 w-nws.webmaster@noaa.gov,urn:oid:2.49.0.1.840.0.01bdffd7ff23f11c313b06b4db41f0ce33539ed6.002.2,2024-04-03T08:27:00-07:00 w-nws.webmaster@noaa.gov,urn:oid:2.49.0.1.840.0.14b605f66a963eb14c531ff29b57d8fa9c7a94b7.002.2,2024-04-03T02:41:00-07:00"
    ]
}
```

**Comment by alexander0042** [comment]
Ok, took a look at this and the data is already ingested into the API (returned as "title"), which is great! Just need to check what's going into the alerts sensor
