### ISSUE TITLE
Alert Sensor Documentation

### ISSUE THREAD

**Issue by phurth** [Pirate-Weather/pirate-weather-ha#211]
### Describe the issue

I have the integration set up to create a weather entity, but have the monitored condition of `Alerts` set up to create a sensor. Currently, there are no alerts for my location, so I'm not surprised that there is no alert sensor that has been created. However, to test, I set up a new integration with the same settings but for a location that does have an active alert (Bangor, Maine - all of Maine seems to be having a winter storm). Still nothing.

So, my question is what should I expect to see if there is an alert when I have this configured to create a sensor for the monitored condition of `Alerts`? A new entity named something like `sensor.name_of_the_location_alerts`?

### Home Assistant version

2024.4.0

### Integration version

1.4.5.1

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Looks like this issue got skipped. @alexander0042 mentioned in issue #208 that he was going to look at the alerts sensor but hasn't replied back yet.

For the location you tested did you check the API in the browser to confirm that the API is returning an alert? According to this comment https://github.com/Pirate-Weather/pirate-weather-ha/issues/209#issuecomment-2042732221 only zone based alerts are being integrated into the API at the moment.

**Comment by phurth** [comment]
I went back into the configuration for my location and checked `Sensor` under `Weather Entity and/or Sensor Entity.` This, along with having `Alerts` selected under `Monitored Conditions` is doing the trick. I now have a separate sensor for alerts for the location. For what it's worth, it wasn't obvious to me that *both* options needed to be set.

**Comment by cloneofghosts** [comment]
Glad to know you got it working. I've tagged this one with the documentation label since the documentation is lacking on the HA side of things.
