### ISSUE TITLE
Possible integration outage?

### ISSUE THREAD

**Issue by jhemak** [Pirate-Weather/pirate-weather-ha#218]
### Describe the issue

Is the integration down or is it just me?  All sensors have gone unavailable and this is in the debug log:

`2024-04-19 02:50:39.099 DEBUG (MainThread) [custom_components.pirateweather.weather_update_coordinator] Finished fetching pirateweather data in 0.180 seconds (success: False)`

### Home Assistant version

2024.4.3

### Integration version

1.4.5.1

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Are you still having issues with the integration or has everything come back online? If you are can you give your approximate location so I can try to see if I get an error querying the API.

The production API sometimes has momentary outages which is what you may have experienced. The good news is that V2 of the API should be coming online today which will fix these issues.

**Comment by jhemak** [comment]
Yes, it is still down for me with the same error as noted above. I am in the US.

**Comment by cloneofghosts** [comment]
It's possible that you may have hit the API limit depending on the update rate you set for the integration. When you setup the integration what did you set the update rate to? If you query the API in your browser does it work or do you get an error message?

**Comment by jhemak** [comment]
It’s set to 300 seconds, but I do have the integration set up twice - once for a weather entity and another for a set of condition sensors. Maybe that is my mistake?  Could you help me with the format of a test URL?

**Comment by cloneofghosts** [comment]
Here's a URL you can use to query the API to see if you've hit the limit or not: https://api.pirateweather.net/forecast/[API_KEY]/[LAT],[LON]

It's quite possible that with your setup you hit the API limit. There's also not a need to have a second integration as you can have a weather entity and sensors in one integration. it's also not recommended to have the update interval below 15m as the models the API uses only has data in 15m intervals. If you want to change the update interval you'd have to remove and setup the integration again as there is no way to change it after its been setup.

**Comment by jhemak** [comment]
Thanks ... the browser test confirmed it's an API Rate Limit issue.  I updated to a single integration instance with a 15 min polling interval.  That should fix it moving forward.  Thanks for the guidance!

**Comment by mermelmadness** [comment]
I had the same issue.  The odd part is that I've had this integration set up exactly the same way since December, and this is the first month I've run into the API limit.
