### ISSUE TITLE
Add V2 Data Point Sensors

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-ha#224]
### Describe the feature

With the release of API version 2.0.1 there have been fire index fields added to the API when using the `verion=2` query string. A sensor should be added to the integration so the data could be displayed in the API.

Data is only available in the US and parts of Canada at the moment. See https://github.com/Pirate-Weather/pirateweather/issues/119 for more information.

### Acknowledgements

- [X] I have searched this repository and [API Repository](https://github.com/Pirate-Weather/pirateweather/) to see if the feature has already been requested.
- [X] This featre request is sepecific to the HA Integration.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
I figured it'd make more sense to add all the new V2 data points in as sensors all at once instead of starting with the fire index and adding the others later.

I started adding them in the v2-features branch but I don't have a container setup yet for HA so I cannot verify that they work without issue.

**Comment by jhemak** [comment]
I updated and added all sensors to the configuration ... however, after reboot I see only Fire Index and Smoke Index as entities.  None of the accumulation entities or the fire/smoke max.  Am I doing something wrong, or is that expected at this point?

**Comment by cloneofghosts** [comment]
Do you have hourly or daily sensors setup? The accumulation sensors are only available in the hourly and daily blocks. If you don't have hourly or daily sensors enabled then they won't show up in the list.

I have daily sensors setup on my HA install and I see the accumulation senors setup after I enabled them. Before merging in the PR I tested in a devcontainer and the hourly and daily accumulation sensors worked.

**Comment by jhemak** [comment]
OK - that explains it!  I do not have hourly or daily sensors setup... only the "monitored conditions" sensors plus a daily and hourly forecast sensor I created using the get_forecasts service.
