### ISSUE TITLE
Cloud coverage sensor does not contain state_class which prevents it from being stored in long-term statistics

### ISSUE THREAD

**Issue by dimatx** [Pirate-Weather/pirate-weather-ha#226]
### Describe the issue

Noticed that the cloud coverage sensor does not seem to be persisted beyond the ~10 days in recorder. Seems like it's because it does not have state_class="measurement".

![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/24803941/8f12a559-33b4-4cc2-ab9e-4416c063028b)

### Home Assistant version

2024.4.4

### Integration version

1.4.6

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/), [parameter documentation](https://web.archive.org/web/20230128172320/https://www.home-assistant.io/integrations/weather.darksky/) and [sensor documentation](https://web.archive.org/web/20230326100953/https://www.home-assistant.io/integrations/darksky) before opening this issue.
- [X] I have searched this repository and [Pirate Weather Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have checked to see if the issue is not an API issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
This should be fairly easy to setup. Is there any other sensors besides that one you would like that state_class added to?

**Comment by dimatx** [comment]
Awesome. Thanks @cloneofghosts! Might make sense to add this to any that have a measurement value as it then makes then work with long-term stats out of the box. What do you think? In any case, these are the ones I personally have enabled:

- Apparent Temperature
- Cloud Coverage
- Pressure
- Temperature
- UV Index

**Comment by cloneofghosts** [comment]
It's pretty straight forward to setup so I was thinking of adding it to all of the numeric sensors except for maybe the nearest storm sensors.

**Comment by dimatx** [comment]
Makes sense to me. And thanks again!
