### ISSUE TITLE
Precipitation Today Sensor

### ISSUE THREAD

**Issue by jhemak** [Pirate-Weather/pirate-weather-ha#229]
### Describe the issue

I'm sorry that I keep coming up with more questions for you guys!  But, hopefully it shows I'm using this excellent integration/API and perhaps the questions are contributing to the knowledge base for others.

Anyway, with all the precipitation and accumulation options in the integration now, is there any built-in or recommended way to determine the total amount of rainfall in the current day and/or in the past 24 hours?  Reading the documentation, I had thought precipAccumulation might provide this for the current day (I was honing in on the word "total"), but based on https://github.com/Pirate-Weather/pirateweather/issues/205 it seems the accumulation sensors are always forward looking.  Therefore, I'm wondering if I need to do something on my own in order to answer the question of "How much rain has fallen today?"

**liquidAccumulation**
Only on hourly and daily. The amount of liquid precipitation expected to fall over an hour or a day expressed in centimetres or inches depending on the requested units.

**precipAccumulation**
Only on hourly and daily. The total amount of liquid precipitation expected to fall over an hour or a day expressed in centimetres or inches depending on the requested units.

Thank you!

### Documentation URL

https://docs.pirateweather.net/en/latest/API/#liquidaccumulation

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Yes, the accumulation parameters are forward looking now so will only return the expected accumulation for the rest of the day. There isn't anything in the API currently which says how much precipitation has accumulated in x amount of time. There is #138 which is looking for a similar thing that you are asking for.
