### ISSUE TITLE
When to use _0d/_0h, and when not to?

### ISSUE THREAD

**Issue by Intecpsp** [Pirate-Weather/pirate-weather-ha#231]
### Describe the issue

I've looked around trying to find something telling me which to use, but haven't found anything. What are the use cases for the 2 sensors?

Example: It's currently raining outside where I'm at. I have `sensor.pirateweather_precip_probability` saying 25%, and `sensor.pirateweather_precip_probability_0d` saying 47%. Which of these do I trust? I'm contemplating just getting an average of the 2 and going with that, but I wanted to find the actual use cases for the 2 before I did that.

### Documentation URL

https://pirateweather.net/en/latest/ha/

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

**Comment by Intecpsp** [comment]
To add to this, when should I use the `0h` equivalent?

**Comment by cloneofghosts** [comment]
The HA documentation is quite lacking at the moment but to answer your question:

- `0h` is for the top of the current hour
- `0d` is for the current day
- No suffix is for the current time

For your question:

- `precip_probability` - is the probability of precipitation for the current time
- `precip_probability_0h` - is the probability of precipitation for the current hour
- `precip_probability_0d` - is the maximum probability of precipitation for the rest of the current day

`precip_probability_0d` of 47% means that the maximum probability for the rest of the day is 47%

**Comment by Intecpsp** [comment]
Thank you for the help!

For a little more clarification, when you say "current time", do you mean "right now"? So if I wanted to know what the current weather is, use no suffix, correct?

**Comment by alexander0042** [comment]
Thanks for opening to issue, it really does help focus in on what needs to be clarified! "Current time" means right now, or at least as close to right now as possible. So for example, if you called the API at 2:15 pm, the data would be for:
- `currently`: 2:15 pm
- `0h`: 2:00 pm (start of hour)
- `0d`: 12:00 am (start of day)

`currently` has no suffix, so that's correct

**Comment by Intecpsp** [comment]
Got it, thank you for the clarification!
