### ISSUE TITLE
Support temperature[Low/High]Time and apparentTemperature[Low/High]Time attributes

### ISSUE THREAD

**Issue by raydenl** [Pirate-Weather/pirate-weather-ha#235]
### Describe the feature

It would be great to be able to view these attributes as sensors:

temperatureLowTime
temperatureHighTime
apparentTemperatureLowTime
apparentTemperatureHighTime

### Home Assistant version

2024.3.1

### Integration version

1.5.1

### Acknowledgements

- [X] I have searched this repository and [API Repository](https://github.com/Pirate-Weather/pirateweather/) to see if the feature has already been requested.
- [X] This featre request is sepecific to the HA Integration.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
This has been added to the latest release.
