### ISSUE TITLE
What are the sensor entities called?

### ISSUE THREAD

**Issue by 9812ga98sd** [Pirate-Weather/pirate-weather-ha#245]
### Describe the issue

I have installed via HACS and custom repository.
I have a weather.pirateweather entity.
Where are the sensor.pirateweather.humidity sensors?

### Home Assistant version

2024.6.1

### Integration version

1.5.2

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

**Comment by Divide1990** [comment]
Hello,

I had the same issue. Sensors not showing up even if i ticked the sensor box. I then added the sensors to the configuration.yml file, rebooted and then they were there. After that i removed the sensors from the config rebooted again and they were still there. So that might be a workaround .

Configuration.yml

sensor:
  - platform: pirateweather
    api_key: <APIKEY>
    scan_interval: '00:15:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

**Comment by 9812ga98sd** [comment]
Hi,

I added this:

sensor:
    platform: pirateweather
    api_key: nzoccsh5Dbr3y6cY67DZpYgCAFZyIujX
    scan_interval: '00:15:00'
    monitored_conditions: 
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed
        
to my configuration.yaml and then rebooted HA, not a quick reload.
They showed up.

![image](https://github.com/Pirate-Weather/pirate-weather-ha/assets/31600113/430d20b9-606b-4505-bc08-1f37d9fd3f55)


your code above contained some odd unseen characters so you you may want to copy my code and paste it into your post. The tabs did not show an issue in HA but did stop the entities from working.

**Comment by cloneofghosts** [comment]
Thanks for opening this issue. When you are setting up sensors through the integration UI you need to setup the list of monitored conditions as well as click on the sensors box. If you clicked on the sensors box but didn't add anything to the list of monitored conditions it will not create any sensors for you.

@9812ga98sd I noticed in your last post that you had posted you API key so I edited your post to remove it. In the future please make sure to not post it publicly. Thanks.

**Comment by Divide1990** [comment]
@cloneofghosts Can't believe i missed that... It all works now.

Thanks!

**Comment by 9812ga98sd** [comment]
> Thanks for opening this issue. When you are setting up sensors through the integration UI you need to setup the list of monitored conditions as well as click on the sensors box. If you clicked on the sensors box but didn't add anything to the list of monitored conditions it will not create any sensors for you.
> 
> @9812ga98sd I noticed in your last post that you had posted you API key so I edited your post to remove it. In the future please make sure to not post it publicly. Thanks.

Thanks
