### ISSUE TITLE
Detected that custom integration 'pirateweather' calls async_forward_entry_setup for integration, pirateweather

### ISSUE THREAD

**Issue by dhover** [Pirate-Weather/pirate-weather-ha#273]
### Describe the bug

Warning in log

### Expected behavior

No warnings

### Actual behavior

integrations works fine but warnings

### Home Assistant version

2024.7.4

### Integration version

1.5.3

### Other details

`2024-08-01 14:49:40.820 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'pirateweather' calls async_forward_entry_setup for integration, pirateweather with title: PirateWeather and entry_id: 10e46c8764e4a4edab3a3108534c259b, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/pirateweather/__init__.py, line 122: await hass.config_entries.async_forward_entry_setup(entry, PLATFORMS[1]), please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues`

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Thanks for the report. I've fixed the version and I've released a beta version 1.5.4b1 with the fix. I've tested this on my end in a devcontainer and ran into no issues but it would be nice if you could try on your end to make sure everything is works as it should.

**Comment by dhover** [comment]
I can confirm the error is gone and the integrations is working fine.
Thanks!

**Comment by cloneofghosts** [comment]
Stable version has been released. Thanks for confirming that everything is working fine after the update.
