### ISSUE TITLE
Liquid Accumulation Forecast incorrect 

### ISSUE THREAD

**Issue by Hilo4321** [Pirate-Weather/pirate-weather-ha#285]
### Describe the bug

Comparing expected liquid accumulation to other sources, this is not correct. 

Nearly 2 inches of rain in a day would be quite an event for us here in Wisconsin.

I've seen this enough times to stop dismissing it and get it reported :)

![nT1JsTNka7](https://github.com/user-attachments/assets/37159f70-d4c3-4b5d-b260-519fff53a6dd)

### Expected behavior

Display a reasonable liquid accumulation forecast.

### Actual behavior

Displaying a value that isn't remotely realistic.

### Home Assistant version

2024.7.3

### Integration version

1.5.3

### Other details

By the time I finished writing this report, the accumulation amount for "PirateWeather Liquid Accumulation 0d" dropped to .7008, which is still higher than any source I can find.

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Thanks for creating this issue. Whats happening here is the integration sends a request to get data from the API in scientific units which is then converted to your unit of choice.

When I was setting up the V2 specific sensors I missed converting those sensors from mm to inches. So the value you see there is in mm with inches as the unit. I have a PR ready to merge and will then shortly afterwards release a new version with the fix.

**Comment by Hilo4321** [comment]
Cheers, I appreciate it! I knew it had to be something like that.
