### ISSUE TITLE
Setting up Sensors create an error cannot import name 'fromtimestamp' from 'datetime'

### ISSUE THREAD

**Issue by spunkyvt** [Pirate-Weather/pirate-weather-ha#287]
### Describe the bug

When I try to add the Sensors I am getting

ImportError: cannot import name 'fromtimestamp' from 'datetime' (/usr/local/lib/python3.12/datetime.py)

### Expected behavior

I expected the each sensor to get created

### Actual behavior

ImportError: cannot import name 'fromtimestamp' from 'datetime' (/usr/local/lib/python3.12/datetime.py)

### Home Assistant version

2024.8.2

### Integration version

1.5.5

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
@alexander0042 Was doing some updates with the HA integration yesterday to convert from UNIX time to timestamp as requested in #275 which seems to have caused the issue.

**Comment by alpha520098** [comment]
@alexander0042 after the update, the intergation is not working the only thing it says is the check logs,

So far i've deleted the old and reinstalled it again reusing my api key and still not working 

![Screenshot 2024-08-17 060532](https://github.com/user-attachments/assets/11f8e6ca-d5a0-4dd4-a76d-231232fb2f63)

**Comment by cloneofghosts** [comment]
Just released V1.5.6 which fixes the issue of the sensors not setting up correctly.

@alpha520098 What do the logs say? Is it the same issue as posted above or a different issue? When i was testing the fix on my devcontainer I initially got an issue that scan_interval wasn't defined but editing the integration and applying changes fixed that for me.

**Comment by alpha520098** [comment]
So what i did is go back into HACS redownloaded it and it works, so I am sorry for give you a bum steer 

so happy to report all is right in the world!

**Comment by cloneofghosts** [comment]
Glad to hear your issue is fixed. I did release a new version of the integration which fixes the sensor issue so maybe that's what fixed the issue for you.

**Comment by snigehere** [comment]
> @alexander0042 after the update, the intergation is not working the only thing it says is the check logs,
> 
> So far i've deleted the old and reinstalled it again reusing my api key and still not working
> 
> ![Screenshot 2024-08-17 060532](https://private-user-images.githubusercontent.com/82351866/358703730-11f8e6ca-d5a0-4dd4-a76d-231232fb2f63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NDI4MzcsIm5iZiI6MTcyMzg0MjUzNywicGF0aCI6Ii84MjM1MTg2Ni8zNTg3MDM3MzAtMTFmOGU2Y2EtZDVhMC00ZGQ0LWE3NmQtMjMxMjMyZmIyZjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDIxMDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDFmNzNhN2Q1N2I0MTE4YTY0OGZiOGE2Y2E1ZTFjNjY4N2UxZjBhMmRjMjExNjdmNTVhNWY2MTVkM2E0MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1teBlJ1cP0slijsC0RIr3IOxYyRI-E9UgyYbYtfHOBA)

I had the same issue, tried reliad a couple of times without success.  I then clicked configuration, saved it (didn't change anything) and it all came back to life

**Comment by cloneofghosts** [comment]
If you're seeing the scan_interval KeyError all you need to do is edit the integration and apply changes and it will fix the issue. In 1.5.5 the option to change the scan_interval was added to the integration. If you had already setup the integration before the update it will error out as it doesn't exist yet.

The error with the sensors has been fixed and if you're seeing the error you can post here: #290

**Comment by jazzyisj** [comment]
The format for  high temperature time sensors has been updated to datetime but the "forecast time" and daily low temperature time sensors have not.

<img width="420" alt="image" src="https://github.com/user-attachments/assets/03620974-37d8-4a63-b209-b32acb66fe7d">
<img width="412" alt="image" src="https://github.com/user-attachments/assets/f141d070-0914-4923-9709-c34866a1f0a6">
<img width="416" alt="image" src="https://github.com/user-attachments/assets/0371fd03-fc85-4999-ae8f-e92c25a59728">
<img width="421" alt="image" src="https://github.com/user-attachments/assets/44cd7537-150f-4c45-9faa-40bcaca8443d">
