### ISSUE TITLE
Cant get sensors to work

### ISSUE THREAD

**Issue by Tobe2d** [Pirate-Weather/pirate-weather-ha#294]
### Describe the issue

I have installed it using HACS and configured it as shown in the screenshot below:
![image](https://github.com/user-attachments/assets/405a259e-99d7-4548-b3ba-3e86a241afba)

I can see 1 entity but I cant see any sensors.

![image](https://github.com/user-attachments/assets/e2c5641d-3a17-4f1b-b5ec-ffa84bfd2035)

Even when I check in entities

![image](https://github.com/user-attachments/assets/c718f701-274f-41f3-a13d-587d0c4ea740)

What am I missing?

I tick the sensor in configurations like in the 1st screenshot. Hope someone can guide me to get the sensors working.

### Home Assistant version

2024.8.2

### Integration version

1.5.7

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
For the sensors to appear you need to select a list of conditions you wish to monitor in the Monitored Conditions box. If you need to setup hourly or daily sensors then fill in the daily and hourly boxes.

**Comment by Tobe2d** [comment]
Thank you so much @cloneofghosts I've totally missed this. now I see the sensors.
