### ISSUE TITLE
`sourceTimes` sensor

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-ha#296]
### Describe the feature

I'm not sure how possible it would be but it would be nice to have a `sourceTimes` sensor (or sensors) to show when the models used for your forecast were last updated.

### Home Assistant version

2024.8.2

### Integration version

1.5.7

### Acknowledgements

- [X] I have searched this repository and [API Repository](https://github.com/Pirate-Weather/pirateweather/) to see if the feature has already been requested.
- [X] This featre request is sepecific to the HA Integration.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
This is actually super doable! The data is all there, and the framework for adding sensors is plenty established, so mostly just adding entries to a list. 

The complicated part is that the [Python module we're using in Home Assistant](https://github.com/ZeevG/python-forecast.io)  doesn't support the flags attribute. I can work around this by just parsing the raw JSON, but it is a reminder that we really should create an "official" Python wrapper for Pirate Weather. It wouldn't be a massive project, and a [few are already floating around](https://github.com/bakobako/pirate-weather-python?tab=readme-ov-file), but would make things like this easier, as well as future maintenance issues.

**Comment by alexander0042** [comment]
Ok, just pushed a commit that includes these, let me know if it works! 

I can't always get changes in quickly, but I really try to work yours in whenever it's relatively easy 😃

**Comment by cloneofghosts** [comment]
Tested in my devcontainer and they're working. Thanks.
![image](https://github.com/user-attachments/assets/f0c117d3-0123-49e3-9337-301594f1457c)
