### ISSUE TITLE
Fire index value sensor

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirate-weather-ha#297]
I've been monitoring the data and it's been bang on.  It's even picking up that I'm in a small higher risk pocket!

<img width="319" alt="image" src="https://github.com/Pirate-Weather/pirateweather/assets/44064559/0d5858cc-f4b7-4aa9-9843-426cab2762bc">

One addition that might be useful is a fire risk level sensor, or maybe that value can just be included as an attribute to the fire index sensors.  Most people won't understand how the fire index correlates to the more meaningful risk level.   I suppose this could be covered in the docs as well so one could just create their own template sensor if needed.

<img width="229" alt="image" src="https://github.com/Pirate-Weather/pirateweather/assets/44064559/b6cfa439-ac67-489a-a541-a10ceaa065dd">

The OpenUV integration does something similar.

<img width="263" alt="image" src="https://github.com/Pirate-Weather/pirateweather/assets/44064559/956bf0ea-542a-4569-9cee-f7ca2f89fcdc">

I've already done it in a template for myself.

```
template:
  - sensor:
      - name: "Fire Risk Level"
        unique_id: fire_risk_level
        icon: mdi:fire
        state: >
          {% set level = states('sensor.pirateweather_fire_index') | int(-1) %}
          {% if level >= 30 %} Extreme
          {% elif level >= 20 %} Very High
          {% elif level >= 10 %} High
          {% elif level >= 5 %} Moderate
          {% else %} Low
          {% endif %}
        availability: "{{ is_number(states('sensor.pirateweather_fire_index')) }}"
```

This is how I end up displaying it in the HA ui.

<img width="412" alt="image" src="https://github.com/Pirate-Weather/pirateweather/assets/44064559/9a5d0f60-01e2-4082-a0e1-c82f3ecd8d70">

_Originally posted by @jazzyisj in https://github.com/Pirate-Weather/pirateweather/issues/119#issuecomment-2088343476_

**Comment by cloneofghosts** [comment]
Looks like this comment from @jazzyisj got missed from back in May. I remember trying to look into this but couldn't figure anything out.

I'll ping @alexander0042 to see if it's something that could be setup.

**Comment by cloneofghosts** [comment]
@alexander0042 Just wanted to check in to see if this is possible? I've setup the Fire Index template provided above but would be nice if it could be available natively.

If it is possible it may make sense to integrate a global fire index source before adding this to the integration.

**Comment by alexander0042** [comment]
This is very possible! I'm adding a sensor into 1.6.0 that does this now. 

Do you have a source for those risk levels? Just to document where they come from?

**Comment by cloneofghosts** [comment]
Not sure. I just created an issue from the comment that @jazzyisj left in the fire index issue in the main repo.

**Comment by alexander0042** [comment]
I see that now! I just referenced the comment, the levels seem reasonable to me, so I'm on board! 

This is included in 1.6.0 PR, and added to the docs (I remembered for once!)

**Comment by jazzyisj** [comment]
@alexander0042  

**Just to document where they come from?**

https://cwfis.cfs.nrcan.gc.ca/maps/fm3?type=fwih

<img width="635" alt="image" src="https://github.com/user-attachments/assets/c9f24892-dbb9-4294-b7bf-5b90ed93abe6">

**Comment by cloneofghosts** [comment]
@alexander0042 Posted this in the other issue but maybe it got missed:

Did a quick test and it seems to work though after I added the fire index sensor the fire index level sensor wasn't added and I see no way to select it.
