### ISSUE TITLE
Random graph spikes

### ISSUE THREAD

**Issue by mrsofa** [Pirate-Weather/pirate-weather-ha#312]
### Describe the issue

I have these ongoing random spikes of values on every entity, they are random.
Any solution? did I miss anything?
![2](https://github.com/user-attachments/assets/ed64527e-ac43-4662-8954-8a49ced2962d)
![1](https://github.com/user-attachments/assets/433efb3e-2ee5-4efe-bb8c-ea63e1ffd0ab)

### Home Assistant version

2024.9.1

### Integration version

1.5.8

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
Thanks for the report. It's probably related to the API returning extreme results as of this morning (see https://github.com/Pirate-Weather/pirateweather/issues/332). @alexander0042 will need to see what's going on and fix the issue.
