### ISSUE TITLE
Sensor entities missing

### ISSUE THREAD

**Issue by simplemice** [Pirate-Weather/pirate-weather-ha#322]
### Describe the issue

new clear install

![Screenshot from 2024-10-04 23-52-51](https://github.com/user-attachments/assets/d37adc03-8826-4128-ab6d-e32c19bc9bb6)
![Screenshot from 2024-10-04 23-52-07](https://github.com/user-attachments/assets/468f751c-c593-47cd-9c91-bb3473cd3e2f)

### Home Assistant version

2024.10.0

### Integration version

latest

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
The integration does not create sensors out of the box. You need to select the conditions you wish to create sensors for in the monitored conditions box. If you need daily or hourly sensors then you need to fill in the hourly and daily forecasts box.

The HACS configuration for the integration can be found here: https://pirateweather.net/en/latest/ha/#hacs-configuration

**Comment by dxmnkd316** [comment]
@simplemice  - you might want to delete those screenshots unless you have dummy data in the lat/long.
