### ISSUE TITLE
Pressure reading "spikes" at over 3000hPa every week

### ISSUE THREAD

**Issue by speedbird182** [Pirate-Weather/pirate-weather-ha#330]
### Describe the bug

Every week at midnight on Monday morning (00:00:xx) the pressure reading jumps to over 3000hPa before returning to normal.  This reading of over 3000hPa then causes the display history to be completely unreadable.

![image](https://github.com/user-attachments/assets/4a0f4ae4-b9fd-419a-ac31-535b67241d21)

![image](https://github.com/user-attachments/assets/a0ae1f4c-bdc9-4a59-bac1-998db3aa66f1)

### Expected behavior

values with such a high jump (200% increase) should be ignored/dropped as being invalid.

### Actual behavior

Any value is recorded and skews the data

### Home Assistant version

2024.10.3

### Integration version

1.6

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by alexander0042** [comment]
Thanks for posting this issue, and I'm sorry that you're running into it! The good news here is that this sort of long term, periodic thing is exactly what I need to diagnose the problem, so it's very, very helpful. 

I'll investigate and let you know, but I've got a theory about what's happening here

**Comment by alexander0042** [comment]
One interesting aspect to this is that it's occurring at 00:00 local time, not UTC like the API runs in. Do you mind letting me know what location you're querying data for?

**Comment by alexander0042** [comment]
One other helpful troubleshooting step here- would you be able to add in two hourly pressure sensors, for 0 and 1 hours? That way we could get a better handle about what the API is "seeing" at that moment

**Comment by radumarinoiu** [comment]
I am also encountering this same issue, but with all the live sensors I'm using from PirateWeather:
- Apparent Temperature
- Humidity
- Temperature
![image](https://github.com/user-attachments/assets/44f3ee13-8f0b-4f26-a368-6c8128bb8415)
![image](https://github.com/user-attachments/assets/dd74cbaf-5551-4c7e-ac3b-e2fdb58e39e2)
I'm querying the API from Romania (UTC+2)

Also I cannot find a pattern to how often this is happening, except for the fact that it happens at midnight local time for me as well

![image](https://github.com/user-attachments/assets/ebfea4a4-c90a-4442-af38-8e9e891d1bae)

Those 3 sensors above are the only ones exhibiting this issue. Here's a list of all the sensors I have enabled:
![image](https://github.com/user-attachments/assets/81b18887-ccf6-4db4-acf8-8b1b70e576f2)

Let me know if there's anything more I can help with

**Comment by speedbird182** [comment]
> I'm querying the API from the UK (Currently UTC+1). I've set up the pressure sensors for hours 0 and 1 as I don't have them configured. I'll let you know how this goes next week (BST ends and goes back to being GMT/UTC this weekend)

After the UK went back to GMT this weekend, this issue didn't happen overnight.

**Comment by alexander0042** [comment]
What a strange bug! It looks like it's happening at 00:00:19 local- can you confirm that it's just for a single timestep, or does it show up for a while?

**Comment by alexander0042** [comment]
Ah, ha- got it!!! https://api.pirateweather.net/forecast/APIKEY/47.1756,27.594,1731880810 gives the incorrect values- it must have to do with my daily interpolation near zero. Fixing now

**Comment by alexander0042** [comment]
Got it! Float roundoff error in the currently calculation, fixed in version 2.4.0 (live on dev now)

**Comment by alexander0042** [comment]
Should have clarified that- the version number I referenced is the API version number that provides the data for this integration, which was what the issue was with here. 

I don't think there's any way to easily flip the HA integration over to the new source, but the new API version will go live in the next week, so it'll be fixed shortly
