### ISSUE TITLE
Can’t add as repo

### ISSUE THREAD

**Issue by Legion-is-life** [Pirate-Weather/pirate-weather-ha#351]
### Describe the bug

![IMG_5270](https://github.com/user-attachments/assets/c099e6ce-bf17-498a-8158-22cf6fa74175)

### Expected behavior

Tried to add per docs

### Actual behavior

Says not a valid repo. 

### Home Assistant version

2024.11.4

### Integration version

0

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

**Comment by cloneofghosts** [comment]
You need to add the integration as a custom repository in [HACS](https://hacs.xyz/) and from there you can install the integration.

Checking my HA install PW isn't showing up as a custom integration so it may come by default in HACS now.
