### ISSUE TITLE
Daily Forecast Timezone Issue

### ISSUE THREAD

**Issue by gist-ha** [Pirate-Weather/pirate-weather-ha#36]
When deploying in HA weather card, the card is showing "yesterday" as Day 0 in the forecast.  This seems to be due to timestamps being returned by the pirateweather api being 7am GMT and then subtracting the local timezone from that which makes the current daily forecast show yesterday. 

Is this something configurable?

Thanks!

**Comment by gist-ha** [comment]
Here's what I see in Lovelace (at 12:17pm on Thu 1/20):

![image](https://user-images.githubusercontent.com/97122650/150406920-fc360edd-c4f7-463a-905b-7fe23a749d2b.png)

At the same time I pull this from the API directly:

![image](https://user-images.githubusercontent.com/97122650/150407166-ee7f5eaf-aafe-4875-94a3-3454fd6ef072.png)

Which shows the TZ as "America/Denver" which aligns w/ the HA install, with "current" time in GMT, but even converting GMT to "America/Denver" at this point would still be Thu.

Thoughts?
Thanks!

**Comment by alexander0042** [comment]
This one is so weird- that's definitely the correct API response, since 12 pm Denver is 7 pm UTC on the same day, so it's getting the correct data. But for some reason the HA card thinks that time is actually a day behind what it should be.

You're not seeing anything in the HA core logs right? And have you noticed if it's always exactly one day behind, or does it change depending on the time of day

**Comment by jwmcintosh** [comment]
I am just setting up pirate on my own instance and also seeing this same result (shows yesterday always). Any pointers to help narrow this down?

**Comment by motionbluur** [comment]
I'm still having this issue with the daily forecast showing yesterday but with the correct forecast. The hourly forecast reports the correct day and time

**Comment by cloneofghosts** [comment]
@motionbluur Approximately where are you located? Querying the API in the browser what does the API show for your timezone and what does the time parameter show for the first block in the daily section? For the time parameter it'd be helpful to run it through https://www.epochconverter.com/ to convert it to a human-readable date.

**Comment by motionbluur** [comment]
> @motionbluur Approximately where are you located? Querying the API in the browser what does the API show for your timezone and what does the time parameter show for the first block in the daily section? For the time parameter it'd be helpful to run it through https://www.epochconverter.com/ to convert it to a human-readable date.

I'm in the Chicago area, central time. The API reports back time zone America/Detroit which is Eastern time, so that's off by 1 hour. However, in the daily section, it reports the time as 17 hours ago (queried Feb 10 at 1600, reports back Feb 9 at 2300)

**Comment by cloneofghosts** [comment]
I figured that the issue might be timezone related. I'll push out an update shortly to use the precise timezone which should fix the issue.

**Comment by motionbluur** [comment]
@cloneofghosts looks like it's working now, thanks!

**Comment by cloneofghosts** [comment]
I'm going to close this one for now as switching to the precise timezone has fixed the issue. There are still some other daily forecast timezone API issues which should hopefully be sorted out in the 2.0 release. See https://github.com/Pirate-Weather/pirateweather/issues/114 and https://github.com/Pirate-Weather/pirateweather/issues/32
