### ISSUE TITLE
Incorrect weather for Rantoul, IL during ongoing heatwave

### ISSUE THREAD

**Issue by NCC1941** [Pirate-Weather/pirate-weather-ha#50]
Over the last couple of days, my area has gotten significantly hotter, but Pirate Weather's info doesn't seem to be keeping up. PW temperature info was very similar to NWS info up until June 13th, where it gave strange fluctuating readings from about 1:30PM-5:30PM. Since then, PW temperature data has looked believable on a graph, aside from the fact that it no longer lines up with the NWS readings, nor my own perception.

![image](https://user-images.githubusercontent.com/90672258/173883243-badb987b-ab88-4c16-b24f-58368970905e.png)

I don't have a local outdoor temperature sensor to compare to, but this change has had a significant adverse effect on my cooling automations, so between that experience and the NWS readings, I'm reasonably sure that the more recent PW readings are the inaccurate ones.

![image](https://user-images.githubusercontent.com/90672258/173884484-e0a6e7f8-b823-4994-bfe4-6591b728bc04.png)

**Comment by NCC1941** [comment]
Small update: I've pulled a few more temperature sensors from other weather providers and Pirate Weather continues to be the clear outlier.

![image](https://user-images.githubusercontent.com/90672258/173969893-f4e94651-6ae7-4087-8f2b-f486f30eb3fd.png)


I'm also getting some interesting results from weather.pirateweather.net.

If I let the site auto-detect my location, I get the following, which generally agrees with what I'm seeing in HA: 
![image](https://user-images.githubusercontent.com/90672258/173970513-9e2f1006-b14e-41a9-825a-1028104b1a50.png)

But if I type in 'Rantoul, IL' manually, I get this, which seems much closer to reality:

![image](https://user-images.githubusercontent.com/90672258/173970634-56b8e5cb-d344-4d4e-b252-f92b877c8e12.png)

**Comment by alexander0042** [comment]
Hi- thank you so much for opening this, and
apologies for not replying sooner (I was
camping last week, so far away from cell
reception)! One of the hardest parts of making
a weather API is being able to validate the
results at a wide number of locations, so
reports like these are really helpful.

To start with, let's figure out why you're
getting those two locations, since that's
particularly weird. Do you know how to use the developer tools in your browser? If you watch the API calls, it’ll show the specific latitude and longitudes that are called, which will let us tell what location it’s looking for

**Comment by alexander0042** [comment]
Perfect, that does help actually! Typing "Rantoul, IL" in I'm getting a lat long of: 40.3083672, -88.1558785, which is about 2.4 miles off the other location:

![image](https://user-images.githubusercontent.com/26213938/175075215-e98a5608-bb78-42fe-b607-fda584f93f7c.png)

That's pretty close by, but just far enough to fall into a different model grid, which explains the results you're seeing at least! To check it out, here are two different observations for those points: [7RMC+PR Rantoul, IL](https://www.tropicaltidbits.com/analysis/models/sounding/?model=hrrr&runtime=2022062214&fh=5&lat=40.2&lon=-88.1&stationID=&tc=&mode=regular) and:[Rantoul, IL](https://www.tropicaltidbits.com/analysis/models/sounding/?model=hrrr&runtime=2022062214&fh=5&lat=40.3&lon=%20-88.15&stationID=&tc=&mode=regular) which are very similar, but ever so slightly different. 

I'll double check the back end to make sure the API isn't grabbing the wrong grid cell here (which has happened before), but we might have to chalk this one up to the intricacies of the HRRR model. It seems like the entire modelling suite is struggling a little bit with the heat wave (<https://twitter.com/webberweather/status/1536347235713224717?s=20&t=SE-7pF1MRz0HJeZ0elqtBw>); however, I'm not enough of an atmospheric scientist to figure that one out.

The good news on this front is that I'm working on implementing a new source for the current conditions (Issue #30). It won't help with the forecasts, but should make current conditions in the US much more accurate, and will be online by early fall!

**Comment by BruceHowells** [comment]
For what it may be worth, seeing similar confusion for "Salem, OR, USA" - even tried a few locations nearby.  At 2:49pm Pacific, PirateWeather is reporting 62 deg F, while NWS reports 75 and AccuWeather, 73.  (Sorry, I'm not quite enough of a weather nerd to pull the surface number out of the HRRR soundings.)

**Comment by BruceHowells** [comment]
> For what it may be worth, seeing similar confusion for "Salem, OR, USA" - even tried a few locations nearby. At 2:49pm Pacific, PirateWeather is reporting 62 deg F, while NWS reports 75 and AccuWeather, 73. (Sorry, I'm not quite enough of a weather nerd to pull the surface number out of the HRRR soundings.)

And, of course, as soon as I commented...  it resolved.  Two charts attached - 7 day comparison of met.no, PirateWeather and OWM (the rest of history is just as boring, good agreement between all three until early on 7/23), and the second drilled down on the past 24h.  Everyone was tracking well until around 9am local, when PW got "stuck" on 62, and then resumed good agreement with the other sources between 14:36 and 15:12.

![temps last 24 recovery](https://user-images.githubusercontent.com/13401442/180624812-0222e447-1c61-4de6-b750-f9a622f52bba.png)
![temps last week](https://user-images.githubusercontent.com/13401442/180624814-12e31814-22e6-4d67-87be-7c5cdcef8e15.png)
.

**Comment by cloneofghosts** [comment]
I'm going to close this issue for cleanup. The 2.0 API version will have weather model improvements which should hopefully improve things. If you want to follow along you can here https://github.com/Pirate-Weather/pirateweather/issues/75 and https://github.com/Pirate-Weather/pirateweather/issues/117
