### ISSUE TITLE
Sensors for temperature low/high doesn't work

### ISSUE THREAD

**Issue by Spirituss** [Pirate-Weather/pirate-weather-ha#99]
I choose sensors "temperature high", "temperature low", "apparent temp low", "apparent temp high", but nothing of them did appeared in HA.

**Comment by kvanhoorn** [comment]
Configured it today, could find templow in attributes but no temphigh

**Comment by Spirituss** [comment]
Bump

**Comment by alexander0042** [comment]
Thanks for the bump- I've assigned it to myself to make sure it doesn't go stale again, but this remains at the top of the priority list!

**Comment by cloneofghosts** [comment]
I know it's been a while but I'm wondering if you're still having issues with the sensors. I just tested adding these sensors on my HA install and I can see data for all four sensors.

Out of curiosity what does your configuration screen look like? These sensors are daily sensors so you'll have to have entered in a number in the daily sensors box. So for example if you want the current day high/low you'll want to enter in 0 in the daily box.

**Comment by cloneofghosts** [comment]
Haven't heard anything since I posted my last comment so I will close this issue. If you're still having issues with the sensors feel free to reply and we can re-open this issue.
